version: "3.0"

expectations:
  population_size: 1000

actions:
  query_tpp:
    run: >
      sqlrunner:latest
        --output output/results_tpp.csv
        --dummy-data-file analysis/dummy_results.csv
        analysis/query_tpp.sql
    outputs:
      moderately_sensitive:
        results: output/results_tpp.csv
