version: "3.0"

expectations:
  population_size: 1000

actions:
  query_practice_registrations:
    run: >
      sqlrunner:latest
        --output output/results_practice_registrations.csv
        --dummy-data-file analysis/dummy_results.csv
        analysis/query_practice_registrations.sql
    outputs:
      moderately_sensitive:
        results: output/results_practice_registrations.csv
